config:
  cleaner:
    empty-chats-clean-delay: 3600 # delay for clean empty chats in db (time unit - seconds)
  jwt:
    secret: someSecret # jwt secret (size >= 256 bits)
    expiration-time-seconds: 600000 # token expiration time (min value: 300, default value: 3600)

server:
  port: 8080 # the port on which the application will run

spring:
  datasource:
    driver-class-name: org.postgresql.Driver # or your DB driver
    url: jdbc:postgresql://localhost:5432/<some_db> # or your JDBC-url and DB
    username: db_username # your username
    password: db_password # your password
  jpa:
    show-sql: true

springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs